RozetkaWebApp/Models/Property.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace RozetkaWebApp.Models
{
    public partial class Property
    {
        public Property()
        {
            Characteristics = new HashSet<Characteristic>();
        }

        public int PropertyId { get; set; }
        public int CatalogId { get; set; }
        public string Title { get; set; }
        public string Label { get; set; }
        public string Category { get; set; }
        public string Format { get; set; }
        public string Mask { get; set; }
        public bool? IsNumber { get; set; }
        public string Description { get; set; }

        public virtual Catalog Catalog { get; set; }
        public virtual ICollection<Characteristic> Characteristics { get; set; }
    }
}

RozetkaWebApp/Controllers/PropertiesController.cs
//MLHIDEFILE
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RozetkaWebApp.Data;
using RozetkaWebApp.Models;
using System.Linq;
using System.Threading.Tasks;

namespace RozetkaWebApp.Controllers
{
    [Authorize(Roles = "Користувачі")]
    public class PropertiesController : Controller
    {
        private readonly RozetkadbContext _context;

        public PropertiesController(RozetkadbContext context)
        {
            _context = context;
        }

        // GET: Properties
        public async Task<IActionResult> Index(int? id, string Filter = null, int page = 0, int pageSize = 20)
        {
            if (id != null) ViewBag.Catalog = _context.Catalogs.Include(c => c.Portal).First(i => i.CatalogId == id);
            var applicationDbContext = _context.Properties.Where(c => c.CatalogId == id || id == null).Include(c => c.Catalog);
            ViewBag.Filter = Filter;
            ViewBag.Page = page;
            ViewBag.PageSize = pageSize;
            var query = applicationDbContext.Where(x => Filter == null || x.Label.Contains(Filter));
            ViewBag.TotalCount = query.Count();
            return View(await query.OrderBy(x => x.Label).Skip(pageSize * page).Take(pageSize).ToListAsync());
        }

        // GET: Properties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var property = await _context.Properties
                .Include(pp => pp.Catalog)
                .FirstOrDefaultAsync(m => m.PropertyId == id);
            if (property == null)
            {
                return NotFound();
            }
            ViewBag.Catalog = _context.Catalogs.Include(c => c.Portal).First(i => i.CatalogId == property.CatalogId);
            return View(property);
        }
        [Authorize(Roles = "Маркетологи")]

        // GET: Properties/Create
        public IActionResult Create(int? Id)
        {
            var catalog = _context.Catalogs.Include(c => c.Portal).FirstOrDefault(m => m.CatalogId == Id);
            ViewBag.Catalog = catalog;
            ViewBag.CatalogId = new SelectList(_context.Catalogs.Where(i => i.PortalId == catalog.PortalId), "CatalogId", "Label");
            return View();
        }
        [Authorize(Roles = "Маркетологи")]

        // POST: Properties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PropertyId,CatalogId,Title,Label,Format,IsNumber,Description")] Property @property, string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@property);
                await _context.SaveChangesAsync();
                if (returnUrl != null) return Redirect(returnUrl);
                return Redirect($"/Properties/Index/" + @property.CatalogId);
            }
            ViewBag.CatalogId = new SelectList(_context.Catalogs, "CatalogId", "Label", @property.CatalogId);
            return View(@property);
        }
        [Authorize(Roles = "Маркетологи")]

        // GET: Properties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var property = await _context.Properties.FindAsync(id);
            if (property == null)
            {
                return NotFound();
            }
            ViewBag.Catalog = _context.Catalogs.Include(c => c.Portal).First(i => i.CatalogId == property.CatalogId);
            ViewBag.CatalogId = new SelectList(_context.Catalogs.Where(i => i.PortalId == property.Catalog.PortalId), "CatalogId", "Label");
            return View(property);
        }
        [Authorize(Roles = "Маркетологи")]

        // POST: Properties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PropertyId,CatalogId,Title,Label, Category, Format, Mask, IsNumber,Description")] Property @property, string returnUrl = null)
        {
            if (id != @property.PropertyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@property);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropertyExists(@property.PropertyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (returnUrl != null) return Redirect(returnUrl);
                 return Redirect($"/Properties/Index/" + @property.CatalogId);
            }
            ViewBag.CatalogId = new SelectList(_context.Catalogs, "CatalogId", "Label", @property.CatalogId);
            return View(@property);
        }
        [Authorize(Roles = "Маркетологи")]

        // GET: Properties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var property = await _context.Properties
                .Include(pp => pp.Catalog)
                .FirstOrDefaultAsync(m => m.PropertyId == id);
            if (property == null)
            {
                return NotFound();
            }
            ViewBag.Catalog = _context.Catalogs.Include(c => c.Portal).First(i => i.CatalogId == property.CatalogId);
            return View(property);
        }
        [Authorize(Roles = "Маркетологи")]

        // POST: Properties/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, string returnUrl = null)
        {
            var @property = await _context.Properties.FindAsync(id);
            id = @property.CatalogId;
            _context.Properties.Remove(@property);
            await _context.SaveChangesAsync();

            if (returnUrl != null) return Redirect(returnUrl);
            return Redirect($"/Properties/Index/" + id);

        }

        private bool PropertyExists(int id)
        {
            return _context.Properties.Any(e => e.PropertyId == id);
        }
    }
}

RozetkaWebApp/Views/Properties/Create.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model RozetkaWebApp.Models.Property


@{
    ViewBag.FiltersTab = (("active"));
    Html.RenderPartial((("_CatologNavigator")));
}

<p>
    <h4> @Resources.Новый_фильтр </h4>
</p>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div class="form-group">
                <input type="submit" value="@Resources.Create" class="btn btn-success" />
                <button type="button" class="btn btn-primary" onclick="history.go(-1)">@Resources.Отменить</button>
                <hr />
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="display: none">
                <label asp-for="CatalogId" class="control-label">@Resources.Каталог0</label>
                @*              <select asp-for="CatalogId" class ="form-control" asp-items="ViewBag.CatalogId"></select>*@
                <input asp-for="CatalogId" class="form-control" value=@ViewBag.Catalog.CatalogId />
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label">@Resources.Заголовок0</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Label" class="control-label">@Resources.Этикетка</label>
                <input asp-for="Label" class="form-control" />
                <span asp-validation-for="Label" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label">@Resources.Категория</label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mask" class="control-label">@Resources.Маска_ввода</label>
                <input asp-for="Mask" class="form-control" />
                <span asp-validation-for="Format" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Format" class="control-label">@Resources.Формат_вывода</label>
                <input asp-for="Format" class="form-control" />
                <span asp-validation-for="Format" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsNumber" class="control-label">@Resources.Это_число</label>
                <input asp-for="IsNumber" class="form-control" />
                <span asp-validation-for="IsNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">@Resources.Описание</label>
                <div>
                    <textarea asp-for="Description" rows="6" style="width:100%"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
    await Html.RenderPartialAsync((("_ValidationScriptsPartial")));
}
}

RozetkaWebApp/Views/Properties/Delete.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model RozetkaWebApp.Models.Property

@{
    ViewBag.FiltersTab = (("active"));
    Html.RenderPartial((("_CatologNavigator")));
}

<p></p>

<p> <h4>@Resources.Удалить_этот_фильтр</h4> </p>

<div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="PropertyId" />
        <input type="submit" value="@Resources._Remove" class="btn btn-danger" />
        <button type="button" class="btn btn-primary" onclick="history.go(-1)">@Resources.Отменить</button>
        <hr />
    </form>
    <p></p>

    <dl class="row">
        <dt class="col-sm-2"> @Resources.Каталог0  </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Catalog.Label) </dd>
        <dt class="col-sm-2"> @Resources.Заголовок0  </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Title) </dd>
        <dt class="col-sm-2"> @Resources.Этикетка </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Label) </dd>
        <dt class="col-sm-2"> @Resources.Маска_ввода </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Mask) </dd>
        <dt class="col-sm-2"> @Resources.Формат_вывода </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Format) </dd>
        <dt class="col-sm-2"> @Resources.Это_число </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.IsNumber) </dd>
        <dt class="col-sm-2"> @Resources.Описание </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Description) </dd>
    </dl>

</div>

RozetkaWebApp/Views/Properties/Details.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model RozetkaWebApp.Models.Property
@{
    ViewBag.FiltersTab = (("active"));
    Html.RenderPartial((("_CatologNavigator")));
}
<p></p>

<div>
    <a asp-action="Edit" asp-route-id="@Model.PropertyId">Edit</a> |
    <a asp-action="Index">@Resources.Back_to_List</a>
    <hr />
</div>

<div>
    <dl class="row">
        <dt class="col-sm-2"> @Resources.Каталог0  </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Catalog.Label) </dd>
        <dt class="col-sm-2"> @Resources.Заголовок0  </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Title) </dd>
        <dt class="col-sm-2"> @Resources.Этикетка </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Label) </dd>
        <dt class="col-sm-2"> @Resources.Маска_ввода </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Mask) </dd>
        <dt class="col-sm-2"> @Resources.Формат_вывода </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Format) </dd>
        <dt class="col-sm-2"> @Resources.Это_число </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.IsNumber) </dd>
        <dt class="col-sm-2"> @Resources.Описание </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Description) </dd>
    </dl>
</div>

RozetkaWebApp/Views/Properties/Edit.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model RozetkaWebApp.Models.Property

@{
    ViewBag.FiltersTab = (("active"));
    Html.RenderPartial((("_CatologNavigator")));
}

<p>
    <h4> @Resources.Изменить_фильтр </h4>
</p>

<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <input type="hidden" name="returnUrl" value="@Context.Request.Headers["Referer"].ToString()" /> 

            <div class="form-group">
                <input type="submit" value="@Resources.Сохранить" class="btn btn-success" />
                <button type="button" class="btn btn-primary" onclick="history.go(-1)">@Resources.Отменить</button>
                <hr />
            </div>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PropertyId" />
            <div class="form-group" style="display: none">
                <label asp-for="CatalogId" class="control-label">@Resources.Каталог0</label>
                <select asp-for="CatalogId" class="form-control" asp-items="ViewBag.CatalogId"></select>
                <span asp-validation-for="CatalogId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label">@Resources.Заголовок0</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Label" class="control-label">@Resources.Этикетка</label>
                <input asp-for="Label" class="form-control" />
                <span asp-validation-for="Label" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label">@Resources.Категория</label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Format" class="control-label">@Resources.Формат_вывода</label>
                <input asp-for="Format" class="form-control" />
                <span asp-validation-for="Format" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mask" class="control-label">@Resources.Маска_ввода</label>
                <input asp-for="Mask" class="form-control" />
                <span asp-validation-for="Mask" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsNumber" class="control-label"> @Resources.Это_число</label>
                <input asp-for="IsNumber" class="form-control" />
                <span asp-validation-for="IsNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">@Resources.Описание</label>
                <div>
                    <textarea asp-for="Description" rows="6" style="width:100%"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
    await Html.RenderPartialAsync((("_ValidationScriptsPartial")));
}
}

RozetkaWebApp/Views/Properties/Index.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model IEnumerable<RozetkaWebApp.Models.Property>

@{
    ViewBag.FiltersTab = (("active"));
    Html.RenderPartial((("_CatologNavigator")));

    <p><h4>@Resources.Список_фильтров</h4></p>

    Html.RenderPartial((("_FilterNavigator")));
}



<table class="table table-sm table-hover">
    <thead>
        <tr>
            <th> @Resources.ID </th>
            <th> @Resources.Наименование_фильтра </th>
            <th> @Resources.Формат_вывода </th>
            <th> @Resources.Маска_ввода  </th>
            <th class="text-right"> @Resources.Действия </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td> @Html.DisplayFor(modelItem => item.PropertyId)  </td>
                <td> <a asp-controller="Properties" asp-action="Edit" asp-route-id="@item.PropertyId">@Html.DisplayFor(modelItem => item.Label) </a> </td>
                <td> @Html.DisplayFor(modelItem => item.Format)  </td>
                <td>  @Html.DisplayFor(modelItem => item.Mask)  </td>
                <td class="text-right small">
                    <a asp-action="Edit" asp-route-id="@item.PropertyId">   <i class="fas fa-solid fa-pen-square m-1"></i> </a>  
                 @{
                     string itemPath = "/properties/delete/"+item.PropertyId.ToString();
                     <partial name="_LinkDelete" model="@itemPath" />
                 }
                </td>
            </tr>
        }
    </tbody>
</table>