RozetkaWebApp/Models/Catalog.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace RozetkaWebApp.Models
{
    public partial class Catalog
    {
        public Catalog()
        {
            CatalogImages = new HashSet<CatalogImage>();
            Products = new HashSet<Product>();
            Properties = new HashSet<Property>();
        }

        public int CatalogId { get; set; }
        public int PortalId { get; set; }
        public string Title { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public string Attributes { get; set; }

        public virtual Portal Portal { get; set; }
        public virtual ICollection<CatalogImage> CatalogImages { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
    }
}

RozetkaWebApp/Models/Characteristic.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace RozetkaWebApp.Models
{
    public partial class Characteristic
    {
        public long CharacteristicId { get; set; }
        public long ProductId { get; set; }
        public int PropertyId { get; set; }
        public string Value { get; set; }
        public string Dimension { get; set; }

        public virtual Product Product { get; set; }
        public virtual Property Property { get; set; }
    }
}

RozetkaWebApp/Controllers/CatalogsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RozetkaWebApp.Data;
using RozetkaWebApp.Models;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace RozetkaWebApp
{
    [Authorize(Roles = "Користувачі")]

    public class CatalogsController : Controller
    {
        private readonly RozetkadbContext _context;

        public CatalogsController(RozetkadbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? id, string Filter = null, int page = 0, int pageSize = 20)
        {
            ViewBag.Portal = _context.Portals.Find(id);
            var applicationDbContext = _context.Catalogs.Where(c => c.PortalId == id || id == null).Include(c => c.Portal);
            ViewBag.Filter = Filter;
            ViewBag.Page = page;
            ViewBag.PageSize = pageSize;
            var query = applicationDbContext.Where(x => Filter == null || x.Label.Contains(Filter));
            ViewBag.TotalCount = query.Count();
            return View(await query.OrderBy(x => x.Label).Skip(pageSize * page).Take(pageSize).ToListAsync());
        }

        public async Task<FileResult> Image(int? id)
        {
            if (id == null) return null;
            var image = await _context.CatalogImages.FirstOrDefaultAsync(m => m.Id == id);
            if (image == null) return null;
            System.IO.MemoryStream oMemoryStream = new System.IO.MemoryStream(image.Data);
            return new FileStreamResult(oMemoryStream, "image/*");
        }

        public async Task<IActionResult> Details(int? id, string Filter = null, int page = 0, int pageSize = 20, string chioces = null, string orderBy = null)
        {
            if (id == null) return NotFound();
            var catalog = await _context.Catalogs
                .Include(c => c.Portal)
                .FirstOrDefaultAsync(c => c.CatalogId == id);
            if (catalog == null) return NotFound();
            ViewBag.Filter = Filter;
            ViewBag.Selectors = _context.Filters.Where(c => c.CatalogId == id).ToList();
            ViewBag.Page = page;
            ViewBag.PageSize = pageSize;
            ViewBag.Chioces = chioces;
            ViewBag.Portal = catalog.Portal;
            ViewBag.OrderBy = orderBy;
            var query = _context.Products.Include(x => x.Comments).Where(x => x.CatalogId == id).Where(x => Filter == null || x.Label.Contains(Filter));
            if (chioces != null)
            {
                var chiocesList = chioces.Split('|').Select(x => new { group = x.Split("=") }).Where(x => x.group.Length == 2);
                var filterSet = _context.Characteristics.Select(x => new
                {
                    ProductId = x.ProductId,
                    PropertyId = x.PropertyId,
                    Value = (x.Value+ x.Dimension).Replace("+","").Replace("&", "").Replace("?", "").Replace("=", "").Replace(" ","")
                });
                foreach (var propertyId in chiocesList.Select(x => x.group[0]).Distinct())
                {
                    var valueSet = chiocesList.Where(c => c.group[0] == propertyId).Select(x => x.group[1]);
                    var productSet = filterSet.Where(x => (x.PropertyId.ToString() == propertyId && valueSet.Contains(x.Value))).Select(x => x.ProductId);
                    query = query.Where(x => productSet.Contains(x.ProductId));
                }
            }
            if (orderBy?.ToUpper() == "PRICEDOWN")
                query = query.OrderBy(x => x.Price);
            else
                if (orderBy?.ToUpper() == "PRICEUP")
                query = query.OrderByDescending(x => x.Price);
            else
                if (orderBy?.ToUpper() == "RATING")
                query = query.OrderByDescending(x => x.Comments.Average(x=>x.Score));
            else
                if (orderBy?.ToUpper() == "POPULARITY")
                query = query.OrderByDescending(x => x.ViewCount);
            else
                 if (orderBy?.ToUpper() == "NOVILTY")
                query = query.OrderByDescending(x => x.ProductId);
            else
                 if (orderBy?.ToUpper() == "PROMOTION")
                query = query.OrderBy(x => x.Label).OrderByDescending(x => x.Promotion);
            else
                query = query.OrderBy(x => x.Label);
            var products = query.Skip(pageSize * page).Take(pageSize);
            ViewBag.TotalCount = products.Count();
            ViewBag.Products = products.ToList();
            ViewBag.Advertising = _context.Products.Include(x=> x.Comments).OrderByDescending(x => x.ChoiceCount).Take(6).ToList();
            return View(catalog);
        }

        [Authorize(Roles = "Маркетологи")]
        public IActionResult Create(int? Id)
        {
            var catalog = _context.Portals.FirstOrDefault(m => m.PortalId == Id);
            ViewBag.Portal = catalog;
            ViewBag.PortalId = new SelectList(_context.Portals, "PortalId", "Label");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CatalogId,PortalId,Title,Label,Description,Attributes")] Catalog catalog,string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                _context.Add(catalog);
                await _context.SaveChangesAsync();
                if (returnUrl != null) return Redirect(returnUrl);
                return Redirect($"/Catalogs/Index/" + catalog.PortalId);
            }
            ViewBag.PortalId = new SelectList(_context.Portals, "PortalId", "Label", catalog.PortalId);
            return View(catalog);
        }

        [Authorize(Roles = "Маркетологи")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var catalog = await _context.Catalogs
                .Include(c => c.Portal)
                .FirstOrDefaultAsync(m => m.CatalogId == id);
            if (catalog == null) return NotFound();
            ViewBag.PortalId = new SelectList(_context.Portals, "PortalId", "Label", catalog.PortalId);
            return View(catalog);
        }

        [Authorize(Roles = "Маркетологи")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CatalogId,PortalId,Title,Label,Description,Attributes")] Catalog catalog, string returnUrl = null)
        {
            if (id != catalog.CatalogId) return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(catalog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CatalogExists(catalog.CatalogId)) return NotFound();
                    else throw;
                }
                if (returnUrl != null) return Redirect(returnUrl);
                return Redirect($"/Catalogs/Index/" + catalog.PortalId);
            }
            ViewBag.PortalId = new SelectList(_context.Portals, "PortalId", "Label", catalog.PortalId);
            return View(catalog);
        }


        [Authorize(Roles = "Маркетологи")]
        public async Task<IActionResult> Delete(int? id, string Filter = null, int page = 0, int pageSize = 20, string chioces = null)
        {
            if (id == null) return NotFound();
            var catalog = await _context.Catalogs
                .Include(c => c.Portal)
                .FirstOrDefaultAsync(m => m.CatalogId == id);
            if (catalog == null) return NotFound();
            ViewBag.Selectors = _context.Filters.Where(c => c.CatalogId == id).ToList();
            ViewBag.Filter = Filter;
            ViewBag.Page = page;
            ViewBag.PageSize = pageSize;
            ViewBag.Portal = catalog.Portal;
            ViewBag.Chioces = chioces;
            var query = _context.Products.Where(x => x.CatalogId == id).Where(x => Filter == null || x.Label.Contains(Filter));
            if (chioces != null)
            {
                var chiocesList = chioces.Split('|').Select(x => new { group = x.Split("=") }).Where(x => x.group.Length == 2);
                var filterSet = _context.Characteristics.Select(x => new
                {
                    ProductId = x.ProductId,
                    PropertyId = x.PropertyId,
                    Value = (x.Value + x.Dimension).Replace("+", "").Replace("&", "").Replace("?", "").Replace("=", "").Replace(" ", "")
                });
                foreach (var propertyId in chiocesList.Select(x => x.group[0]).Distinct())
                {
                    var valueSet = chiocesList.Where(c => c.group[0] == propertyId).Select(x => x.group[1]);
                    var productSet = filterSet.Where(x => (x.PropertyId.ToString() == propertyId && valueSet.Contains(x.Value))).Select(x => x.ProductId);
                    query = query.Where(x => productSet.Contains(x.ProductId));
                }
            }
            var products = query.OrderBy(x => x.Label).Skip(pageSize * page).Take(pageSize);
            ViewBag.TotalCount = products.Count();
            ViewBag.Products = products.ToList();
            ViewBag.Advertising = _context.Products.OrderByDescending(x => x.ChoiceCount).Take(6).ToList();
            return View(catalog);
        }


        [Authorize(Roles = "Маркетологи")]
        [HttpPost, ActionName("Delete")]
    //    [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, string returnUrl = null)
        {
            var catalog = await _context.Catalogs.FindAsync(id);
            var Id = catalog.PortalId;
            _context.Catalogs.Remove(catalog);
            await _context.SaveChangesAsync();

RozetkaWebApp/Controllers/PortalsController.cs
//MLHIDEFILE
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RozetkaWebApp.Data;
using RozetkaWebApp.Models;
using System.Linq;
using System.Threading.Tasks;

namespace RozetkaWebApp
{
    [Authorize(Roles = "Користувачі")]
    public class PortalsController : Controller
    {
        private readonly RozetkadbContext _context;

        public PortalsController(RozetkadbContext context)
        {
            _context = context;
        }

        [HttpGet("[controller]/Home")]
        public async Task<IActionResult> Home(string Filter = null, int page = 0, int pageSize = 20)
        {
            var applicationDbContext = _context.Portals;

            ViewBag.Filter = Filter;
            ViewBag.Page = page;
            ViewBag.PageSize = pageSize;
            var query = applicationDbContext.Where(x => Filter == null || x.Label.Contains(Filter));
            ViewBag.TotalCount = query.Count();
            //if (id == null) id = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.User = _context.AspNetUsers.Where(x=>x.UserName == User.Identity.Name).First();
            ViewBag.Advertising = _context.Products.Include(x => x.Comments).OrderByDescending(x => x.ProductId).Take(4).ToList();
            ViewBag.Advertising1 = _context.Products.Include(x => x.Comments).OrderByDescending(x => x.PromotionId).Take(4).ToList();
            return View(await query.OrderBy(x => x.Label).Skip(pageSize * page).Take(pageSize).ToListAsync());
        }

        // GET: Portals
        [HttpGet("[controller]/Index")]
        public async Task<IActionResult> Index(string Filter = null, int page = 0, int pageSize = 20)
        {
            var applicationDbContext = _context.Portals;

            ViewBag.Filter = Filter;
            ViewBag.Page = page;
            ViewBag.PageSize = pageSize;
            var query = applicationDbContext.Where(x => Filter == null || x.Label.Contains(Filter));
            ViewBag.TotalCount = query.Count();
            return View(await query.OrderBy(x => x.Label).Skip(pageSize * page).Take(pageSize).ToListAsync());
        }

        // GET: Portals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var portal = await _context.Portals.Include(m => m.Catalogs)
                .FirstOrDefaultAsync(m => m.PortalId == id);
            if (portal == null)
            {
                return NotFound();
            }
            ViewBag.Advertising = _context.Products
                .Include(x => x.Comments)
                .OrderByDescending(x => x.ChoiceCount).Take(6).ToList();
            return View(portal);
        }

        // GET: Portals/Create
        [Authorize(Roles = "Маркетологи")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Portals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PortalId,Title,Label,Description,Attributes")] Portal portal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(portal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(portal);
        }

        [Authorize(Roles = "Маркетологи")]
        // GET: Portals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var portal = await _context.Portals.FindAsync(id);
            if (portal == null)
            {
                return NotFound();
            }
            return View(portal);
        }

        // POST: Portals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Маркетологи")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PortalId,Title,Label,Description,Attributes")] Portal portal, string returnUrl = null)
        {
            if (id != portal.PortalId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(portal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PortalExists(portal.PortalId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (returnUrl != null) return Redirect(returnUrl);
                return RedirectToAction(nameof(Index));
            }
            return View(portal);
        }

        [Authorize(Roles = "Маркетологи")]
        // GET: Portals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)  return NotFound();
             var portal = await _context.Portals.Include(m => m.Catalogs)
                .FirstOrDefaultAsync(m => m.PortalId == id);
            if (portal == null) return NotFound();
            ViewBag.Advertising = _context.Products.OrderByDescending(x => x.ChoiceCount).Take(6).ToList();
            return View(portal);
        }

        [Authorize(Roles = "Маркетологи")]
        // POST: Portals/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var portal = await _context.Portals.FindAsync(id);
            _context.Portals.Remove(portal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PortalExists(int id)
        {
            return _context.Portals.Any(e => e.PortalId == id);
        }
    }
}

RozetkaWebApp/Views/Home/Carts.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model IEnumerable<RozetkaWebApp.Models.LineDetail>

@{
    ViewBag.ManagerTab = (("active"));
    Html.RenderPartial((("_CartNavigator")));
}

<p><h4>@Resources.Список_выбраных_товаров</h4></p>

<p><a class="btn btn-success" asp-controller="Home" asp-action="NewOrder"> @Resources.Оформить_заказ </a>   </p>


<table class="table">
    <thead>
        <tr>
            <th> @Resources.Заголовок0 </th>
            <th> @Resources.Описание </th>
            <th> @Resources.Цена </th>
            <th> @Resources.Количество  </th>
            <th> @Resources.Дата  </th>
            <th>  @Resources.Действия </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitCost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantities)
                </td>
                <td>
                    @(((DateTime)item.CreateDate).ToString((("dd/MM/yyyy"))))
                </td>
                <td>
                    <a asp-controller="LineDetails" asp-action="Edit" asp-route-id="@item.OrderDatailId"><i class="fas fa-solid fa-pen-square m-1"></i></a> |
                    <a asp-controller="LineDetails" asp-action="Details" asp-route-id="@item.OrderDatailId"><i class="fas fa-solid fa-folder m-1"></i></a> |
                    <a asp-controller="LineDetails" asp-action="Delete" asp-route-id="@item.OrderDatailId"><i class="fas fa-solid fa-trash m-1"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

RozetkaWebApp/Views/Home/Catalogs.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model IEnumerable<RozetkaWebApp.Models.Catalog>

@{
    ViewBag.Title = Resources.Каталог0;
}

<h1>@Resources.Каталоги</h1>


<table class="table">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Home" asp-action="Products" asp-route-id="@item.CatalogId">@Html.DisplayFor(modelItem => item.Title)</a>
                </td>
            </tr>
        }
    </tbody>
</table>

RozetkaWebApp/Views/Home/Characteristics.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model IEnumerable<RozetkaWebApp.Models.Characteristic>

@{
    ViewBag.Title = Resources.Характеристики;
}

<h1> @Resources.Детально_о_товаре </h1>

<p><a class="btn btn-success" asp-controller="Home" asp-action="AddToCart" asp-route-id="@ViewBag.Product.ProductId"> @Resources.Купить </a>   </p>


<table class="table">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <p>@Html.DisplayFor(modelItem => item.Property.Label)</p>
                </td>
                <td>
                    <p>@Html.DisplayFor(modelItem => item.Value)</p>
                </td>
            </tr>
        }
    </tbody>
</table>

RozetkaWebApp/Views/Home/Index.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model IEnumerable<RozetkaWebApp.Models.Portal>

@{
    ViewBag.Title = Resources.Index;
}

<div class="bg-image text-center text-white"
     style="background-image: url('@Url.Content("~/Images/root/background")');
      background-size: cover;
      height: 80vh
      ">

    <div class="d-flex justify-content-center align-items-center h-100 vertical-align: middle ">
        <div style="width: 90%" class="text-left">
            <h1 class="display-2 font-weight-bold font-weight-bolder">   @Resources.BAZAR </h1>
            <p class="display-9 fw-bold fw-bolder"> @Resources.Управління_інтернет_крамницею  </p>
            <br />
            <h1>
                <a type="button" class="btn btn-primary border border-white"
                   asp-area="" asp-controller="Portals" asp-action="Index">@Resources.Управління_веб_контентом</a>
                <a type="button" class="btn btn-outline-primary border border-white text-white"
                   target="acumatica" href="http://vpn.veradata.com:8888/bazar">@Resources.Робота_з_ERP_системою</a>

            </h1>

        </div>
    </div>
</div>


@*<h1>@Resources.Порталы</h1>

    <section class="hero-wrap"
    style="background-image: url('@Url.Content("~/Images/root/background")');" >
    <span class="subheading">Hi There!</span>
    <table class="table">
    <tbody>
    @foreach (var item in Model) {
    <tr>
    <td>
    <a asp-controller = "Home" asp-action="Catalogs" asp-route-id="@item.PortalId">@Html.DisplayFor(modelItem => item.Title)</a>
    </td>
    </tr>
    }
    </tbody>
    </table>
    </section>
*@

RozetkaWebApp/Views/Home/NewOrder.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model RozetkaWebApp.Models.Order

@{
    ViewBag.Title = Resources.Create;
}

<h1>@Resources.Create</h1>

<h4>@Resources.Заказы</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CardNumber" class="control-label"></label>
                <input asp-for="CardNumber" class="form-control" />
                <span asp-validation-for="CardNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryAddress" class="control-label"></label>
                <input asp-for="DeliveryAddress" class="form-control" />
                <span asp-validation-for="DeliveryAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryContact" class="control-label"></label>
                <input asp-for="DeliveryContact" class="form-control" />
                <span asp-validation-for="DeliveryContact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryEmail" class="control-label"></label>
                <input asp-for="DeliveryEmail" class="form-control" />
                <span asp-validation-for="DeliveryEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryPhone" class="control-label"></label>
                <input asp-for="DeliveryPhone" class="form-control" />
                <span asp-validation-for="DeliveryPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExtOrderNbr" class="control-label"></label>
                <input asp-for="ExtOrderNbr" class="form-control" />
                <span asp-validation-for="ExtOrderNbr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Resources.Back_to_List</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync((("_ValidationScriptsPartial")));
}
}

RozetkaWebApp/Views/Home/Portal.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model RozetkaWebApp.Models.Portal

@{
    ViewBag.Title = Resources.Портал;
}

<h1>@Resources.Портал</h1>

<div>
    <h4>@Resources.Портал</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Label)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Label)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Attributes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Attributes)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PortalId">Edit</a> |
    <a asp-action="Index">@Resources.Back_to_List</a>
</div>

RozetkaWebApp/Views/Home/Portals.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model IEnumerable<RozetkaWebApp.Models.Portal>

<h1>@Resources.Порталы</h1>


<table class="table">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Home" asp-action="Catalogs" asp-route-id="@item.PortalId">@Html.DisplayFor(modelItem => item.Title)</a>
                </td>
            </tr>
        }
    </tbody>
</table>

RozetkaWebApp/Views/Home/Products.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model IEnumerable<RozetkaWebApp.Models.Product>

@{
    ViewBag.Title = (("Catalog"));
}

<h1>  @Resources.Товары </h1>


<table class="table">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Home" asp-action="Characteristics" asp-route-id="@item.ProductId">@Html.DisplayFor(modelItem => item.Title)</a>
                </td>
            </tr>
        }
    </tbody>
</table>