RozetkaWebApp/Models/LineDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace RozetkaWebApp.Models
{
    public partial class LineDetail
    {
        public long OrderDatailId { get; set; }
        public long? OrderId { get; set; }
        public string UserId { get; set; }
        public string CartId { get; set; }
        public long ProductId { get; set; }
        [DisplayFormat(DataFormatString = "{0:F0}", ApplyFormatInEditMode = false)]
        public int Quantities { get; set; }
        [DisplayFormat(DataFormatString = "{0:F0}₴", ApplyFormatInEditMode = false)]
        public decimal UnitCost { get; set; }
        public string Status { get; set; }
        public string ExtOrderDetailNbr { get; set; }
        public DateTime? CreateDate { get; set; }

        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}

RozetkaWebApp/Controllers/LineDetailsController.cs
//MLHIDEFILE
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RozetkaWebApp.Data;
using RozetkaWebApp.Models;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace RozetkaWebApp.Controllers
{
    [Authorize(Roles = "Користувачі")]

    public class LineDetailsController : Controller
    {
        private readonly RozetkadbContext _context;

        public LineDetailsController(RozetkadbContext context)
        {
            _context = context;
        }

        public string CartId()
        {
            if (!HttpContext.Request.Cookies.ContainsKey("cartId"))
            {
                var cartId = Guid.NewGuid().ToString();
                HttpContext.Response.Cookies.Append("cartId", cartId);
                return cartId;
            }
            return HttpContext.Request.Cookies["cartId"];
        }
        // GET: LineDetails

        public async Task<IActionResult> Index()
        {
            var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier) ?? "";
            var rozetkadbContext = _context.LineDetails
                .Include(l => l.Order)
                .Include(l => l.Product)
                .Where(l => l.OrderId == null)
                .Where(l => l.CartId == CartId() || (l.UserId == userId));
            ViewBag.User = await _context.AspNetUsers.FindAsync(userId);
            return View(await rozetkadbContext.ToListAsync());

        }

        public async Task<IActionResult> CopyCart()
        {
            var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier) ?? "";
            var lines = _context.LineDetails.Where(l => l.CartId == CartId() && (l.UserId == null)).Select(l => l);
            var views = _context.Views.Where(l => l.CartId == CartId() && (l.UserId == null)).Select(l => l);

            foreach (var i in lines)
            {
                i.UserId = userId;
                _context.Update(i);
            }
            foreach (var i in views)
            {
                i.UserId = userId;
                _context.Update(i);
            }
            await _context.SaveChangesAsync();
            HttpContext.Response.Cookies.Delete("cartId");
            return Redirect("/");
        }

        // GET: LineDetails/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lineDetail = await _context.LineDetails
                .Include(l => l.Order)
                .Include(l => l.Product)
                .FirstOrDefaultAsync(m => m.OrderDatailId == id);
            if (lineDetail == null)
            {
                return NotFound();
            }

            return View(lineDetail);
        }
        [Authorize(Roles = "Продавці")]

        // GET: LineDetails/Create
        public IActionResult Create()
        {
            ViewBag.OrderId = new SelectList(_context.Orders, "OrderId", "DeliveryAddress");
            ViewBag.ProductId = new SelectList(_context.Products, "ProductId", "Label");
            return View();
        }
        [Authorize(Roles = "Продавці")]

        // POST: LineDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderDatailId,OrderId,UserId,CartId,ProductId,Quantities,UnitCost,Status,ExtOrderDetailNbr,CreateDate")] LineDetail lineDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lineDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.OrderId = new SelectList(_context.Orders, "OrderId", "DeliveryAddress", lineDetail.OrderId);
            ViewBag.ProductId = new SelectList(_context.Products, "ProductId", "Label", lineDetail.ProductId);
            return View(lineDetail);
        }
        [Authorize(Roles = "Продавці")]

        // GET: LineDetails/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)  return NotFound();
            var UserId = _context.LineDetails.Find(id).UserId;
            ViewBag.User = _context.AspNetUsers.Find(UserId);
            var lineDetail = await _context.LineDetails.FindAsync(id);
            if (lineDetail == null) return NotFound();
            ViewBag.ProductId = new SelectList(_context.Products, "ProductId", "Label", lineDetail.ProductId);
            return View(lineDetail);
        }
        [Authorize(Roles = "Продавці")]

        // POST: LineDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("OrderDatailId,OrderId,UserId,CartId,ProductId,Quantities,UnitCost,Status,ExtOrderDetailNbr,CreateDate")] LineDetail lineDetail, string returnUrl = null)
        {
            if (id != lineDetail.OrderDatailId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lineDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LineDetailExists(lineDetail.OrderDatailId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (returnUrl != null) return Redirect(returnUrl);
                return Redirect($"/AspNetUsers/Cart/" + lineDetail.UserId);
            }
            ViewBag.OrderId = new SelectList(_context.Orders, "OrderId", "DeliveryAddress", lineDetail.OrderId);
            ViewBag.ProductId = new SelectList(_context.Products, "ProductId", "Label", lineDetail.ProductId);
            return View(lineDetail);
        }
        [Authorize(Roles = "Продавці")]

        // GET: LineDetails/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var UserId = _context.LineDetails.Find(id).UserId;
            ViewBag.User = _context.AspNetUsers.Find(UserId);
            var lineDetail = await _context.LineDetails
                .Include(l => l.Order)
                .Include(l => l.Product)
                .FirstOrDefaultAsync(m => m.OrderDatailId == id);
            if (lineDetail == null)
            {
                return NotFound();
            }

            return View(lineDetail);
        }
        [Authorize(Roles = "Продавці")]

        // POST: LineDetails/Delete/5
        [HttpPost, ActionName("Delete")]
      //  [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id, string returnUrl = null)
        {
            var lineDetail = await _context.LineDetails.FindAsync(id);
            _context.LineDetails.Remove(lineDetail);
            await _context.SaveChangesAsync();
            if (returnUrl != null) return Redirect(returnUrl);
            return Redirect($"/AspNetUsers/Cart/" + lineDetail.UserId);

        }

        private bool LineDetailExists(long id)
        {
            return _context.LineDetails.Any(e => e.OrderDatailId == id);
        }
    }
}

RozetkaWebApp/Views/LineDetails/Delete.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model RozetkaWebApp.Models.LineDetail;

@{
    ViewBag.CartTab = (("active"));
    Html.RenderPartial((("_ProfileNavigator")));

    <p><h4>@Resources.Вы_хотите_удалить_этот_товар_и</h4></p>
}

    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderDatailId" />
        <input type="submit" value="@Resources._Remove" class="btn btn-danger" /> 
        <button type="button" class="btn btn-primary"  onclick= "history.go(-1)">@Resources.Отменить</button>
         <hr />
    </form>
<div>
   
    <dl class="row">       
        <dt class = "col-sm-2">
            @Resources.Заголовок0
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Title)
        </dd >
        <dt class  = "col-sm-2">
            @Resources.Описание
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Description)
        </dd class>
      <dt class = "col-sm-2">
            @Resources.Цена
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitCost)
            </dd>
        <dt class = "col-sm-2">
            @Resources.Количество
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantities)
        </dd>
        <dt class = "col-sm-2">
            @Resources.Сумма
        </dt>
         <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LineTotal)
        </dd>
        
    </dl>
 
</div>

RozetkaWebApp/Views/LineDetails/Details.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model RozetkaWebApp.Models.LineDetail

@{
    ViewBag.ManagerTab = (("active"));
    Html.RenderPartial((("_CartNavigator")));
}

<p> 
    <h4>@Resources.Информация_о_товаре_из_корзины</h4>
</p>

<div>
    <div class="form-group">
          <a class="btn btn-success" asp-action="Edit" asp-route-id="@Model.OrderDatailId"> @Resources.Изменить </a>
           <button type="button" class="btn btn-primary"  onclick= "history.go(-1)">@Resources.Отменить</button>  
           @{
                ViewBag.returnUrl = "/LineDetails/Index/" + Model.OrderDatailId.ToString();
                string Path = "/LineDetails/delete/" + Model.OrderDatailId.ToString();
                <partial name="_ButtonDeleteDetails" model="@Path" />
            } 
           <hr />
      </div>   
    <dl class="row">
               <dt class = "col-sm-2">
            @Resources.Заголовок0
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Title)
        </dd >
        <dt class  = "col-sm-2">
            @Resources.Описание
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Description)
        </dd class>

        <dt class = "col-sm-2">
            @Resources.Цена
        </dt>
         <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitCost)
        </dd>
        <dt class = "col-sm-2">
            @Resources.Количество
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantities)
        </dd> 
        <dt class = "col-sm-2">
            @Resources.Сумма
        </dt>
         <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LineTotal)
        </dd>
        <dt class = "col-sm-2">

    </dl>
</div>

RozetkaWebApp/Views/LineDetails/Edit.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model RozetkaWebApp.Models.LineDetail

@{
    ViewBag.CartTab = (("active"));
    Html.RenderPartial((("_ProfileNavigator")));

    <p><h4> @Resources.Изменить_количество_товара </h4></p>
}




<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" name="returnUrl" value="@Context.Request.Headers["Referer"].ToString()" /> 

            <div class="form-group">
                <input type="submit" value="@Resources.Сохранить" class="btn btn-success" />
                <button type="button" class="btn btn-primary" onclick="history.go(-1)">@Resources.Отменить</button>
                <hr />
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderDatailId" />
            <div class="form-group" style="display: none">
                <label asp-for="OrderId" class="control-label"></label>
                <input asp-for="OrderId" class="form-control"></input>
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>
            <div class="form-group" style="display: none">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group" style="display: none">
                <label asp-for="CartId" class="control-label"></label>
                <input asp-for="CartId" class="form-control" />
                <span asp-validation-for="CartId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label">@Resources.Товар</label>
                <select ReadOnly="false" asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantities" class="control-label">@Resources.Количество</label>
                <input asp-for="Quantities" class="form-control" />
                <span asp-validation-for="Quantities" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitCost" class="control-label">@Resources.Цена</label>
                <input ReadOnly="false" asp-for="UnitCost" class="form-control" />
                <span asp-validation-for="UnitCost" class="text-danger"></span>
            </div>
            <div class="form-group" style="display: none">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group" style="display: none">
                <label asp-for="ExtOrderDetailNbr" class="control-label"></label>
                <input asp-for="ExtOrderDetailNbr" class="form-control" />
                <span asp-validation-for="ExtOrderDetailNbr" class="text-danger"></span>
            </div>
            <div class="form-group" style="display: none">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>

        </form>
    </div>
</div>


@section Scripts {
    @{
    await Html.RenderPartialAsync((("_ValidationScriptsPartial")));
}
}

RozetkaWebApp/Views/LineDetails/Index.cshtml
@using RozetkaWebApp.App_GlobalResources;
@model IEnumerable<RozetkaWebApp.Models.LineDetail>

@{
    ViewBag.ManagerTab = (("active"));
    Html.RenderPartial((("_CartNavigator")));
}

<p><h4>@Resources.Список_выбраных_товаров</h4></p>


@if (ViewBag.User == null)
{
    <p><a class="btn btn-success" asp-area="Identity" asp-page="/Account/Login">@Resources.Оформить_заказ</a>   </p>
}
else
{
    <p><a class="btn btn-success" asp-controller="Orders" asp-action="Create" asp-route-id="@ViewBag.User.Id"> @Resources.Оформить_заказ </a>   </p>
}

<table class="table">
    <thead>
        <tr>
            <th> @Resources.Наименование_товара </th>
            <th> @Resources.Описание </th>
            <th> @Resources.Цена </th>
            <th> @Resources.Количество  </th>
            @*         <th> Дата  </th>  *@
            <th>  @Resources.Сумма </th>
            <th>  @Resources.Действия </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitCost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantities)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LineTotal)
                </td>

                <td>
                    <a asp-controller="LineDetails" asp-action="Edit" asp-route-id="@item.OrderDatailId"><i class="fas fa-solid fa-pen-square m-1"></i></a>
                    <a asp-controller="LineDetails" asp-action="Details" asp-route-id="@item.OrderDatailId"><i class="fas fa-solid fa-folder m-1"></i></a>
                    @{
                        string itemPath = "/LineDetails/delete/" + item.OrderDatailId.ToString();
                        <partial name="_LinkDelete" model="@itemPath" />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>